---
name: Broadcast
author: Josiaah
main: Josiah/Broadcast/main
api: 3.0.0
version: 1.0.0

commands:
  test:
    description: My first plugin in six years
    usage: "/test"
    permission: broadcastplugin.cmd.broadcast

permissions:
  broadcastplugin.cmd.broadcast:
    description: Permission to use /test command
    default: true  
---
